### PR TITLE
Fix: Ignore invalid content (fixes #68)

### LINKED ISSUE #68: Issue with all components when ... is only content in body or other areas
### Subject of the issue/enhancement/features
When using only ... in a component body, or item text it breaks the Search with an error and the course can not search any more. 

### Your environment
FW 5.28.9
Chrome/Edge/Safari/Firefox
PC/MAC

### Steps to reproduce
Type only ... in any component's body area or any where else and I get an error.

### Expected behaviour
Shouldn't have an error when using triple dots (...)

### Actual behaviour
I get the following error in the screenshot below...

### Screenshots (if you can)
searchError

### PR DESCRIPTION
**Pull request by swashbuck**
Fixes #68 

### Fix
* Ignores content (ex. `title`, `body`) if it does not contain any valid characters that pass the regex (ex. one or more alphanumeric characters).
* Suppresses error if `title` or `displayTitle` are missing completely

### Testing
First test
1. Add a `.`, `#`, or `...` to a component's `body` or `title` as the _only_ content.
2. Check the console for errors. You should _not_ see:

```
Uncaught TypeError: this.safePhrase.match(...) is null
```
Second test
1. Remove `title` and `displayTitle` completely from a component
2. Check the console for errors. You should _not_ see:

```
Uncaught TypeError: this.model.get(...) is undefined
```

### CODE REVIEW

File: js/SearchablePhrase.js [hunk 1]
```diff
@@ -29,17 +29,19 @@ export default class SearchablePhrase {
...
+      this.words = matchedWords.map(chunk => chunk.replace(trimReplaceNonWordCharacters, ''))
+        .filter(word => word.length >= minimumWordLength)
+        .reduce((wordCounts, word) => {
+          word = word.toLowerCase();
+          if (ignoreWords.includes(word)) return wordCounts;
+          wordCounts[word] = wordCounts[word] || 0;
+          wordCounts[word]++;
+          return wordCounts;
+        }, {});
+    }
```
Comment (oliverfoster) [inline js/SearchablePhrase.js:44]:
```suggestion
    if (matchedWords === null) return;
    this.words = matchedWords.map(chunk => chunk.replace(trimReplaceNonWordCharacters, ''))
      .filter(word => word.length >= minimumWordLength)
      .reduce((wordCounts, word) => {
        word = word.toLowerCase();
        if (ignoreWords.includes(word)) return wordCounts;
        wordCounts[word] = wordCounts[word] || 0;
        wordCounts[word]++;
        return wordCounts;
      }, {});
```

**Review by oliverfoster — APPROVED** [review]
